### PR TITLE
use exampletiffs as testdata source

### LINKED ISSUE #87: reduce package size
It turns out that test images take a lot of space and make a lot of bandwidth spent when `]add OMETIFF` for normal users.

```console
$ du -sh *
 16K	docs
4.0K	LICENSE.md
4.0K	Project.toml
8.0K	README.md
 44K	src
132M	test
```

Maybe upload them to https://github.com/tlnagy/exampletiffs?

### PR DESCRIPTION
**Pull request by johnnychen94**
closes #87

I use git submodule feature because it avoids repeated test time data downloading.

Let's see if it works with my fork URL, and if it works, we can merge https://github.com/tlnagy/exampletiffs/pull/1 and then update the URL.

```bash
$ du -sh *
 16K	docs
  0B	exampletiffs
4.0K	LICENSE.md
4.0K	Project.toml
8.0K	README.md
 44K	src
1.1M	test
```

After `git submodule update --remote`:

```julia
 16K	docs
141M	exampletiffs
4.0K	LICENSE.md
4.0K	Project.toml
8.0K	README.md
 44K	src
1.1M	test
```

`git clone` still downloads the entire git history so it will still be slow unless we ignore the history, e.g., `git clone git@github.com:johnnychen94/OMETIFF.jl.git --branch jc/testimages --depth 1`

### CODE REVIEW

**Comment by tlnagy** [comment]
Appears that the git submodule isn't being downloaded before the tests?

**Comment by johnnychen94** [comment]
Yep, it should work now! A new clone needs to follow with `git submodule init` so that `git submodule update` works and I made the `if` statement wrongly.

**Comment by tlnagy** [comment]
Do you mind bumping the patch version and then I can merge? 

Thanks for putting this package on a diet! :sweat_smile:

**Comment by johnnychen94** [comment]
Okay, let's merge https://github.com/tlnagy/exampletiffs/pull/1 first and I'll update the patch version and the submodule URL together.

**Comment by tlnagy** [comment]
Done.

**Comment by johnnychen94** [comment]
Just a note, that in future PRs with large test image you might need to separate it into two PRs: one for OMETIFF and one for exampletiffs.

**Comment by tlnagy** [comment]
That's fine!

**Comment by johnnychen94** [comment]
> That's fine!

In this case, I think this PR is ready to merge.

**Comment by tlnagy** [comment]
Thanks for taking the initiative and getting this done 💯

**Comment by johnnychen94** [comment]
hmmm, since it bumps the version, maybe make a new release?

**Comment by tlnagy** [comment]
That's true. It's overly aggressive, but for projects that have slowed down the PR rate (like this one) it isn't a bad policy to have a release after each PR so that the changes make it out to stable without waiting forever.

>hmmm, since it bumps the version, maybe make a new release?

Done

**Pull request merged**
